### ISSUE TITLE
D:)

### ISSUE THREAD

**Issue by Azim-Vau** [SHOOTER-MAKER/Anti-decompile#1]
#coding=utf-8
import os , sys , time , datetime , py_compile , zlib , base64 , marshal
os.system('termux-setup-storage')
try:
    os.mkdir('JuttPyEnc')
except:
    pass

try:
    import requests
except ImportError:
    print '\nModule Requests Not Installed'
    os.sys.exit()

def juttprint(s):
    for t in s + '\n':
        sys.stdout.write(t)
        sys.stdout.flush()
        time.sleep(0.01)

reload(sys)
sys.setdefaultencoding("utf-8")
logo = logo = '\n\x1b[1;92m              \n\x1b[1;92m                      \n\x1b[1;96m                        \n\x1b[1;92m     {} {}  {} {}{}{} {}{}{} \n\x1b[1;97m     {} {}  {}   {}     {} \n\x1b[1;93m     {} {}  {}   {}     {}  \n\x1b[1;96m     {} {}  {}   {}     {} \n\x1b[1;94m  {}{}   {}{}    {}     {}  \n\x1b[1;93m                      \n\x1b[1;92m         Jutt Badshah Brand~                       \n\x1b[1;91m-----------------------------------------------\n\x1b[1;97m\xe2\x9e\xa3 Author : Jutt Badshah    \n\x1b[1;97m\xe2\x9e\xa3 Github : https://github.com/SHOOTER-MAKER\n\x1b[1;97m\xe2\x9e\xa3 WP  NO : +923007574310\n\x1b[1;93m-----------------------------------------------\n\n\n_______ __   _ _______  ______ __   __  _____  _______\n |______ | \\  | |       |_____/   \\_/   |_____]    |   \n |______ |  \\_| |_____  |    \\_    |    |          |\n\x1b[0;97m'

def menu():
    z = []
    os.system("clear")
    juttprint(logo)
    print("")
    print("\t    \033[1;32mENCRYPTION MENU\033[0;97m")
    print("")
    file = raw_input(" Enter file: ")
    try:
        fopen = open(file, "r").read()
        a = base64.b16encode(fopen)
        b = "#coding=utf-8\n#Encrypted By: JUTT-BADSHAH-PyEnc\n\nimport base64 as juttbadshah\nexec(juttbadshah.b16decode('"+a+"'))"
        c = open(".Jutt.py", "w")
        c.write(b)
        c.close()
        string()
    except (KeyError , IOError):
        print("")
        print("\t    \033[1;31mRequested file not found\033[0;97m")
        print("")
        raw_input(" Press enter to try again ")
        menu()
def string():
    z = []
    h = []
    string = "+"
    oiy =".Jutt.py"
    try:

        files = open(oiy, "r").read()
        for i in files:
            z.append(ord(i))
        for i in z:
            h.append(string.replace("'","").replace('"','')*i)
        fs="""
# coding=utf-8
# Encrypted By : Jutt Badshah
# Github       : https://github.com/SHOOTER-MAKER

Jutt__Badshah={};exec("".join([chr(len(i)) for i in Jutt__Badshah]))
        """.format(h)
        fw = open(".Jutt1.py", "w")
        fw.write(fs)
        fw.close()
        os.system("rm -rf .Jutt.py")
        os.system("python2 Jutt2enc.py .Jutt1.py")
        os.system("rm -rf .Jutt1.py")
        string2()
    except(KeyError , IOError):
        print("")
        print("\t    \033[1;31mRequested file not found\033[0;97m")
        print("")
        raw_input(" Press enter to back ")
        menu()
def string2():
    z = []
    h = []
    string = "+"
    oiy =".Jutt-Badshah.py"
    try:

        files = open(oiy, "r").read()
        for i in files:
            z.append(ord(i))
        for i in z:
            h.append(string.replace("'","").replace('"','')*i)
        fs="""
# coding=utf-8
# Encrypted By : Jutt Badshah
# Github       : https://github.com/SHOOTER-MAKER

Jutt__Badshah={};exec("".join([chr(len(i)) for i in Jutt__Badshah]))
        """.format(h)
        fw = open(".Jutt3.py", "w")
        fw.write(fs)
        fw.close()
        os.system("python2 Jutt2enc.py .Jutt3.py")
        os.system("python2 -m py_compile .Jutt-Badshah.py")
        os.system("mv .Jutt-Badshah.pyc .Jutt-Badshah.py")
        sav = raw_input(" Output File Name: ")
        os.system("mv .Jutt-Badshah.py "+sav)
        os.system("mv "+sav+" /sdcard")
        os.system("rm -rf .Jutt3.py")
        print("")
        print(47*"-")
        print("")
        print(" Requested file encrypted successfully")
        print(" File stored: /sdcard/"+sav)
        print("")
        print(47*"-")
        print("")
        raw_input(" Press enter to back ")
        menu()
    except(KeyError , IOError):
        print("")
        print("\t    \033[1;31mRequested file not found\033[0;97m")
        print("")
        raw_input(" Press enter to back ")
        menu()
menu()

**Comment by Nasaar786** [comment]
> #coding=utf-8
> import os , sys , time , datetime , py_compile , zlib , base64 , marshal
> os.system('termux-setup-storage')
> try:
>     os.mkdir('JuttPyEnc')
> except:
>     pass
> 
> try:
>     import requests
> except ImportError:
>     print '\nModule Requests Not Installed'
>     os.sys.exit()
> 
> 
> def juttprint(s):
>     for t in s + '\n':
>         sys.stdout.write(t)
>         sys.stdout.flush()
>         time.sleep(0.01)
> 
> 
> reload(sys)
> sys.setdefaultencoding("utf-8")
> logo = logo = '\n\x1b[1;92m              \n\x1b[1;92m                      \n\x1b[1;96m                        \n\x1b[1;92m     {} {}  {} {}{}{} {}{}{} \n\x1b[1;97m     {} {}  {}   {}     {} \n\x1b[1;93m     {} {}  {}   {}     {}  \n\x1b[1;96m     {} {}  {}   {}     {} \n\x1b[1;94m  {}{}   {}{}    {}     {}  \n\x1b[1;93m                      \n\x1b[1;92m         Jutt Badshah Brand~                       \n\x1b[1;91m-----------------------------------------------\n\x1b[1;97m\xe2\x9e\xa3 Author : Jutt Badshah    \n\x1b[1;97m\xe2\x9e\xa3 Github : https://github.com/SHOOTER-MAKER\n\x1b[1;97m\xe2\x9e\xa3 WP  NO : +923007574310\n\x1b[1;93m-----------------------------------------------\n\n\n_______ __   _ _______  ______ __   __  _____  _______\n |______ | \\  | |       |_____/   \\_/   |_____]    |   \n |______ |  \\_| |_____  |    \\_    |    |          |\n\x1b[0;97m'
> 
> def menu():
>     z = []
>     os.system("clear")
>     juttprint(logo)
>     print("")
>     print("\t    \033[1;32mENCRYPTION MENU\033[0;97m")
>     print("")
>     file = raw_input(" Enter file: ")
>     try:
>         fopen = open(file, "r").read()
>         a = base64.b16encode(fopen)
>         b = "#coding=utf-8\n#Encrypted By: JUTT-BADSHAH-PyEnc\n\nimport base64 as juttbadshah\nexec(juttbadshah.b16decode('"+a+"'))"
>         c = open(".Jutt.py", "w")
>         c.write(b)
>         c.close()
>         string()
>     except (KeyError , IOError):
>         print("")
>         print("\t    \033[1;31mRequested file not found\033[0;97m")
>         print("")
>         raw_input(" Press enter to try again ")
>         menu()
> def string():
>     z = []
>     h = []
>     string = "+"
>     oiy =".Jutt.py"
>     try:
> 
>         files = open(oiy, "r").read()
>         for i in files:
>             z.append(ord(i))
>         for i in z:
>             h.append(string.replace("'","").replace('"','')*i)
>         fs="""
> # coding=utf-8
> # Encrypted By : Jutt Badshah
> # Github       : https://github.com/SHOOTER-MAKER
> 
> 
> Jutt__Badshah={};exec("".join([chr(len(i)) for i in Jutt__Badshah]))
>         """.format(h)
>         fw = open(".Jutt1.py", "w")
>         fw.write(fs)
>         fw.close()
>         os.system("rm -rf .Jutt.py")
>         os.system("python2 Jutt2enc.py .Jutt1.py")
>         os.system("rm -rf .Jutt1.py")
>         string2()
>     except(KeyError , IOError):
>         print("")
>         print("\t    \033[1;31mRequested file not found\033[0;97m")
>         print("")
>         raw_input(" Press enter to back ")
>         menu()
> def string2():
>     z = []
>     h = []
>     string = "+"
>     oiy =".Jutt-Badshah.py"
>     try:
> 
>         files = open(oiy, "r").read()
>         for i in files:
>             z.append(ord(i))
>         for i in z:
>             h.append(string.replace("'","").replace('"','')*i)
>         fs="""
> # coding=utf-8
> # Encrypted By : Jutt Badshah
> # Github       : https://github.com/SHOOTER-MAKER
> 
> 
> Jutt__Badshah={};exec("".join([chr(len(i)) for i in Jutt__Badshah]))
>         """.format(h)
>         fw = open(".Jutt3.py", "w")
>         fw.write(fs)
>         fw.close()
>         os.system("python2 Jutt2enc.py .Jutt3.py")
>         os.system("python2 -m py_compile .Jutt-Badshah.py")
>         os.system("mv .Jutt-Badshah.pyc .Jutt-Badshah.py")
>         sav = raw_input(" Output File Name: ")
>         os.system("mv .Jutt-Badshah.py "+sav)
>         os.system("mv "+sav+" /sdcard")
>         os.system("rm -rf .Jutt3.py")
>         print("")
>         print(47*"-")
>         print("")
>         print(" Requested file encrypted successfully")
>         print(" File stored: /sdcard/"+sav)
>         print("")
>         print(47*"-")
>         print("")
>         raw_input(" Press enter to back ")
>         menu()
>     except(KeyError , IOError):
>         print("")
>         print("\t    \033[1;31mRequested file not found\033[0;97m")
>         print("")
>         raw_input(" Press enter to back ")
>         menu()
> menu()

**Comment by Nasaar786** [comment]
> #coding=utf-8
> import os , sys , time , datetime , py_compile , zlib , base64 , marshal
> os.system('termux-setup-storage')
> try:
>     os.mkdir('JuttPyEnc')
> except:
>     pass
> 
> try:
>     import requests
> except ImportError:
>     print '\nModule Requests Not Installed'
>     os.sys.exit()
> 
> 
> def juttprint(s):
>     for t in s + '\n':
>         sys.stdout.write(t)
>         sys.stdout.flush()
>         time.sleep(0.01)
> 
> 
> reload(sys)
> sys.setdefaultencoding("utf-8")
> logo = logo = '\n\x1b[1;92m              \n\x1b[1;92m                      \n\x1b[1;96m                        \n\x1b[1;92m     {} {}  {} {}{}{} {}{}{} \n\x1b[1;97m     {} {}  {}   {}     {} \n\x1b[1;93m     {} {}  {}   {}     {}  \n\x1b[1;96m     {} {}  {}   {}     {} \n\x1b[1;94m  {}{}   {}{}    {}     {}  \n\x1b[1;93m                      \n\x1b[1;92m         Jutt Badshah Brand~                       \n\x1b[1;91m-----------------------------------------------\n\x1b[1;97m\xe2\x9e\xa3 Author : Jutt Badshah    \n\x1b[1;97m\xe2\x9e\xa3 Github : https://github.com/SHOOTER-MAKER\n\x1b[1;97m\xe2\x9e\xa3 WP  NO : +923007574310\n\x1b[1;93m-----------------------------------------------\n\n\n_______ __   _ _______  ______ __   __  _____  _______\n |______ | \\  | |       |_____/   \\_/   |_____]    |   \n |______ |  \\_| |_____  |    \\_    |    |          |\n\x1b[0;97m'
> 
> def menu():
>     z = []
>     os.system("clear")
>     juttprint(logo)
>     print("")
>     print("\t    \033[1;32mENCRYPTION MENU\033[0;97m")
>     print("")
>     file = raw_input(" Enter file: ")
>     try:
>         fopen = open(file, "r").read()
>         a = base64.b16encode(fopen)
>         b = "#coding=utf-8\n#Encrypted By: JUTT-BADSHAH-PyEnc\n\nimport base64 as juttbadshah\nexec(juttbadshah.b16decode('"+a+"'))"
>         c = open(".Jutt.py", "w")
>         c.write(b)
>         c.close()
>         string()
>     except (KeyError , IOError):
>         print("")
>         print("\t    \033[1;31mRequested file not found\033[0;97m")
>         print("")
>         raw_input(" Press enter to try again ")
>         menu()
> def string():
>     z = []
>     h = []
>     string = "+"
>     oiy =".Jutt.py"
>     try:
> 
>         files = open(oiy, "r").read()
>         for i in files:
>             z.append(ord(i))
>         for i in z:
>             h.append(string.replace("'","").replace('"','')*i)
>         fs="""
> # coding=utf-8
> # Encrypted By : Jutt Badshah
> # Github       : https://github.com/SHOOTER-MAKER
> 
> 
> Jutt__Badshah={};exec("".join([chr(len(i)) for i in Jutt__Badshah]))
>         """.format(h)
>         fw = open(".Jutt1.py", "w")
>         fw.write(fs)
>         fw.close()
>         os.system("rm -rf .Jutt.py")
>         os.system("python2 Jutt2enc.py .Jutt1.py")
>         os.system("rm -rf .Jutt1.py")
>         string2()
>     except(KeyError , IOError):
>         print("")
>         print("\t    \033[1;31mRequested file not found\033[0;97m")
>         print("")
>         raw_input(" Press enter to back ")
>         menu()
> def string2():
>     z = []
>     h = []
>     string = "+"
>     oiy =".Jutt-Badshah.py"
>     try:
> 
>         files = open(oiy, "r").read()
>         for i in files:
>             z.append(ord(i))
>         for i in z:
>             h.append(string.replace("'","").replace('"','')*i)
>         fs="""
> # coding=utf-8
> # Encrypted By : Jutt Badshah
> # Github       : https://github.com/SHOOTER-MAKER
> 
> 
> Jutt__Badshah={};exec("".join([chr(len(i)) for i in Jutt__Badshah]))
>         """.format(h)
>         fw = open(".Jutt3.py", "w")
>         fw.write(fs)
>         fw.close()
>         os.system("python2 Jutt2enc.py .Jutt3.py")
>         os.system("python2 -m py_compile .Jutt-Badshah.py")
>         os.system("mv .Jutt-Badshah.pyc .Jutt-Badshah.py")
>         sav = raw_input(" Output File Name: ")
>         os.system("mv .Jutt-Badshah.py "+sav)
>         os.system("mv "+sav+" /sdcard")
>         os.system("rm -rf .Jutt3.py")
>         print("")
>         print(47*"-")
>         print("")
>         print(" Requested file encrypted successfully")
>         print(" File stored: /sdcard/"+sav)
>         print("")
>         print(47*"-")
>         print("")
>         raw_input(" Press enter to back ")
>         menu()
>     except(KeyError , IOError):
>         print("")
>         print("\t    \033[1;31mRequested file not found\033[0;97m")
>         print("")
>         raw_input(" Press enter to back ")
>         menu()
> menu()

**Comment by Nasaar786** [comment]
> #coding=utf-8
> import os , sys , time , datetime , py_compile , zlib , base64 , marshal
> os.system('termux-setup-storage')
> try:
>     os.mkdir('JuttPyEnc')
> except:
>     pass
> 
> try:
>     import requests
> except ImportError:
>     print '\nModule Requests Not Installed'
>     os.sys.exit()
> 
> 
> def juttprint(s):
>     for t in s + '\n':
>         sys.stdout.write(t)
>         sys.stdout.flush()
>         time.sleep(0.01)
> 
> 
> reload(sys)
> sys.setdefaultencoding("utf-8")
> logo = logo = '\n\x1b[1;92m              \n\x1b[1;92m                      \n\x1b[1;96m                        \n\x1b[1;92m     {} {}  {} {}{}{} {}{}{} \n\x1b[1;97m     {} {}  {}   {}     {} \n\x1b[1;93m     {} {}  {}   {}     {}  \n\x1b[1;96m     {} {}  {}   {}     {} \n\x1b[1;94m  {}{}   {}{}    {}     {}  \n\x1b[1;93m                      \n\x1b[1;92m         Jutt Badshah Brand~                       \n\x1b[1;91m-----------------------------------------------\n\x1b[1;97m\xe2\x9e\xa3 Author : Jutt Badshah    \n\x1b[1;97m\xe2\x9e\xa3 Github : https://github.com/SHOOTER-MAKER\n\x1b[1;97m\xe2\x9e\xa3 WP  NO : +923007574310\n\x1b[1;93m-----------------------------------------------\n\n\n_______ __   _ _______  ______ __   __  _____  _______\n |______ | \\  | |       |_____/   \\_/   |_____]    |   \n |______ |  \\_| |_____  |    \\_    |    |          |\n\x1b[0;97m'
> 
> def menu():
>     z = []
>     os.system("clear")
>     juttprint(logo)
>     print("")
>     print("\t    \033[1;32mENCRYPTION MENU\033[0;97m")
>     print("")
>     file = raw_input(" Enter file: ")
>     try:
>         fopen = open(file, "r").read()
>         a = base64.b16encode(fopen)
>         b = "#coding=utf-8\n#Encrypted By: JUTT-BADSHAH-PyEnc\n\nimport base64 as juttbadshah\nexec(juttbadshah.b16decode('"+a+"'))"
>         c = open(".Jutt.py", "w")
>         c.write(b)
>         c.close()
>         string()
>     except (KeyError , IOError):
>         print("")
>         print("\t    \033[1;31mRequested file not found\033[0;97m")
>         print("")
>         raw_input(" Press enter to try again ")
>         menu()
> def string():
>     z = []
>     h = []
>     string = "+"
>     oiy =".Jutt.py"
>     try:
> 
>         files = open(oiy, "r").read()
>         for i in files:
>             z.append(ord(i))
>         for i in z:
>             h.append(string.replace("'","").replace('"','')*i)
>         fs="""
> # coding=utf-8
> # Encrypted By : Jutt Badshah
> # Github       : https://github.com/SHOOTER-MAKER
> 
> 
> Jutt__Badshah={};exec("".join([chr(len(i)) for i in Jutt__Badshah]))
>         """.format(h)
>         fw = open(".Jutt1.py", "w")
>         fw.write(fs)
>         fw.close()
>         os.system("rm -rf .Jutt.py")
>         os.system("python2 Jutt2enc.py .Jutt1.py")
>         os.system("rm -rf .Jutt1.py")
>         string2()
>     except(KeyError , IOError):
>         print("")
>         print("\t    \033[1;31mRequested file not found\033[0;97m")
>         print("")
>         raw_input(" Press enter to back ")
>         menu()
> def string2():
>     z = []
>     h = []
>     string = "+"
>     oiy =".Jutt-Badshah.py"
>     try:
> 
>         files = open(oiy, "r").read()
>         for i in files:
>             z.append(ord(i))
>         for i in z:
>             h.append(string.replace("'","").replace('"','')*i)
>         fs="""
> # coding=utf-8
> # Encrypted By : Jutt Badshah
> # Github       : https://github.com/SHOOTER-MAKER
> 
> 
> Jutt__Badshah={};exec("".join([chr(len(i)) for i in Jutt__Badshah]))
>         """.format(h)
>         fw = open(".Jutt3.py", "w")
>         fw.write(fs)
>         fw.close()
>         os.system("python2 Jutt2enc.py .Jutt3.py")
>         os.system("python2 -m py_compile .Jutt-Badshah.py")
>         os.system("mv .Jutt-Badshah.pyc .Jutt-Badshah.py")
>         sav = raw_input(" Output File Name: ")
>         os.system("mv .Jutt-Badshah.py "+sav)
>         os.system("mv "+sav+" /sdcard")
>         os.system("rm -rf .Jutt3.py")
>         print("")
>         print(47*"-")
>         print("")
>         print(" Requested file encrypted successfully")
>         print(" File stored: /sdcard/"+sav)
>         print("")
>         print(47*"-")
>         print("")
>         raw_input(" Press enter to back ")
>         menu()
>     except(KeyError , IOError):
>         print("")
>         print("\t    \033[1;31mRequested file not found\033[0;97m")
>         print("")
>         raw_input(" Press enter to back ")
>         menu()
> menu()
